eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

